#include "../compiler_interface.h"

void register_kernel_objects(struct build_state *);

void register_kernel_objects(struct build_state * state){

	/*  Kernel files */
	register_build_target(state, "kernel/kernel.l1", BUILD_TARGET_L1_FILE);
        register_l0_file(state, "test/kernel.l0.js", "jsonpCallback", "jsonp");
        register_l0_file(state, "emulators/c/kernel.l0.c", "data", "c");
        register_l0_file(state, "emulators/python/op_cpu_package/python_l0_module.py", "OpCPUData", "python");
        register_l0_file(state, "emulators/java/OpCPU/KernelData.java", "KernelData", "java");
        register_dependency(state, "test/kernel.l0.js", "kernel/kernel.l1");
        register_dependency(state, "emulators/c/kernel.l0.c", "kernel/kernel.l1");
        register_dependency(state, "emulators/python/op_cpu_package/python_l0_module.py", "kernel/kernel.l1");
        register_dependency(state, "emulators/java/OpCPU/KernelData.java", "kernel/kernel.l1");

	register_build_target(state, "kernel/kernel_interface.l2", BUILD_TARGET_L2_FILE);
	register_build_target(state, "kernel/putchar_nobusy.l2", BUILD_TARGET_L2_FILE);
	register_build_target(state, "kernel/getchar_nobusy.l2", BUILD_TARGET_L2_FILE);
        register_c_to_l2(state, "kernel/filesystem");
        register_c_to_l2(state, "kernel/putchar");
        register_c_to_l2(state, "kernel/main");
        register_c_to_l2(state, "kernel/queue");
        register_c_to_l2(state, "kernel/kernel_state");
        register_c_to_l2(state, "kernel/kernel_impl");
        register_c_to_l2(state, "kernel/user_proc");

	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_namespace_object_ptr_key_value_pair_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_namespace_object_ptr_key_value_pair_binary_search.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_ptr_to_struct_namespace_object_ptr_map.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_void_ptr_to_unsigned_int_key_value_pair_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_void_ptr_to_unsigned_int_key_value_pair_binary_search.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/void_ptr_compare.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/void_ptr_to_unsigned_int_map.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/void_ptr_memory_pool.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_linker_symbol_memory_pool.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_asm_instruction_memory_pool.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_type_description_memory_pool.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_asm_lexer_token_memory_pool.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_parser_node_memory_pool.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_c_lexer_token_memory_pool.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_constant_description_ptr_key_value_pair_binary_search.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_macro_definition_ptr_key_value_pair_binary_search.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_struct_c_lexer_token_ptr_to_struct_c_lexer_token_ptr_key_value_pair_binary_search.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_macro_parameter_ptr_key_value_pair_binary_search.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_special_macro_definition_ptr_key_value_pair_binary_search.l2");
	register_dependency(state, "kernel/kernel.l1", "builtin/signed_division.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_linker_symbol_ptr_key_value_pair_binary_search.l2");
	register_dependency(state, "kernel/kernel.l1", "builtin/signed_less_than.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_constant_description_ptr_key_value_pair_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_macro_definition_ptr_key_value_pair_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_struct_c_lexer_token_ptr_to_struct_c_lexer_token_ptr_key_value_pair_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_macro_parameter_ptr_key_value_pair_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_special_macro_definition_ptr_key_value_pair_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_ptr_to_struct_linker_symbol_ptr_key_value_pair_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_c_lexer_token_ptr_compare.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_ptr_compare.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_int_merge_sort.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_linker_symbol_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_ptr_to_struct_linker_symbol_ptr_map.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_switch_frame_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_type_traversal_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_type_description_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_constant_initializer_level_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_c_lexer_state_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_unsigned_char_list_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_special_macro_definition_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_ptr_to_struct_special_macro_definition_ptr_map.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_struct_c_lexer_token_ptr_list_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_preprocessor_file_context_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_macro_parameter_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_ptr_to_struct_macro_parameter_ptr_map.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_preprocessor_if_branch_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_c_lexer_token_ptr_to_struct_c_lexer_token_ptr_map.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_macro_definition_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_ptr_to_struct_macro_definition_ptr_map.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_parser_operation_stack.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_constant_description_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_ptr_to_struct_constant_description_ptr_map.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_namespace_object_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_normalized_declarator_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_normalized_declaration_element_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_normalized_specifier_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_asm_lexer_token_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_c_lexer_token_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_int_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/struct_preprocessor_macro_level_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/void_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "memory_pool_collection.l2");
	register_dependency(state, "kernel/kernel.l1", "code_generator.l2");
	register_dependency(state, "kernel/kernel.l1", "preprocessor.l2");
	register_dependency(state, "kernel/kernel.l1", "parser.l2");
	register_dependency(state, "kernel/kernel.l1", "heap_memory_pool.l2");
	register_dependency(state, "kernel/kernel.l1", "lexer.l2");
	register_dependency(state, "kernel/kernel.l1", "io.l2");
	register_dependency(state, "kernel/kernel.l1", "libc/getcwd.l2");
	register_dependency(state, "kernel/kernel.l1", "libc/string.l2");
	register_dependency(state, "kernel/kernel.l1", "libc/filesystem.l2");
	register_dependency(state, "kernel/kernel.l1", "filesystem/filesystem_impl.l2");
	register_dependency(state, "kernel/kernel.l1", "libc/fopen.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_ptr_list.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/unsigned_char_list.l2");
	register_dependency(state, "kernel/kernel.l1", "libc/assert.l2");
	register_dependency(state, "kernel/kernel.l1", "builtin/signed_greater_than_or_equal_to.l2");
	register_dependency(state, "kernel/kernel.l1", "builtin/print_decimal.l2");
	register_dependency(state, "kernel/kernel.l1", "builtin/l2/memory_mapped_registers.l2");
	register_dependency(state, "kernel/kernel.l1", "libc/printf.l2");
	register_dependency(state, "kernel/kernel.l1", "builtin/l2/stack.l2");
	register_dependency(state, "kernel/kernel.l1", "builtin/l2/mainstub.l2");
	register_dependency(state, "kernel/kernel.l1", "libc/malloc.l2");
	register_dependency(state, "kernel/kernel.l1", "data-structures/binary_exponential_buffer.l2");
	register_dependency(state, "kernel/kernel.l1", "builtin/signed_greater_than.l2");

	register_dependency(state, "kernel/kernel.l1", "kernel/filesystem.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/putchar.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/main.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/queue.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/kernel_state.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/kernel_impl.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/user_proc.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/kernel_interface.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/putchar_nobusy.l2");
	register_dependency(state, "kernel/kernel.l1", "kernel/getchar_nobusy.l2");
}
