build-builtins: recc
	$(VALGRIND) ./recc builtin/build-script

clean-builtins:
	@rm -f builtin/*.i builtin/*.o builtin/extern_test.l2 builtin/random.l2 builtin/signed_greater_than_or_equal_to.l2 builtin/signed_modulo.l2 builtin/print_bits.l2 builtin/signed_division.l2 builtin/signed_less_than.l2 builtin/print_decimal.l2 builtin/signed_greater_than.l2 builtin/signed_less_than_or_equal_to.l2
